/*
 * Copyright (C) 2025 Nameless Production Committee
 *
 * Licensed under the MIT License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *          http://opensource.org/licenses/mit-license.php
 */
package aigis.open2ch;

import dev.langchain4j.model.chat.request.ResponseFormat;
import dev.langchain4j.model.googleai.GoogleAiGeminiChatModel;
import dev.langchain4j.service.AiServices;
import dev.langchain4j.service.SystemMessage;
import kiss.I;

public class Editor {

    private static final GoogleAiGeminiChatModel MODEL = GoogleAiGeminiChatModel.builder()
            .apiKey(I.env("GeminiAPIKey"))
            .modelName("gemini-2.5-flash-preview-05-20")
            .responseFormat(ResponseFormat.JSON)
            .build();

    public static Topics edit(OpenThread thread) {
        StringBuilder text = new StringBuilder();
        for (OpenComment comment : thread.comments) {
            text.append("#").append(comment.num).append("\n");
            text.append(comment.body).append("\n\n");
        }

        I.info("Analyze [" + thread.title + "] by Gemini.");

        String json = AiServices.create(Editing.class, MODEL).selectTopics(text.toString());
        System.out.println(json);
        return I.json(json, Topics.class);
    }

    interface Editing {
        @SystemMessage("""
                あなたはプロの編集者です、まとめサイトを作成するために提供されたスレッド全文の中から
                話題になっている全てのトピックを挙げてください。（できれば5個以上）

                各トピックに対してキャッチーなタイトルをつけてください。
                そのトピックに関連するコメントは全てコメント番号を関連付けてください、なおコメントの順番は番号順でなくてもよく、意味がわかりやすくなるように入れ替えてもいいです。オチとして使えそうなコメントであれば最後に持ってくること。
                ひとつのトピックに関連づけるコメントは40個を絶対に超えないでください、超えてしまう場合は余計なものを間引いてください。
                強調すべきコメントがあればその番号は負数にしてください。

                JSON形式で情報を返してください。
                [
                    {
                        "title": "キャッチーなタイトル",
                        "comments": [-1, 2, 5, 10, 22, -13]
                    },
                    {
                        "title": "キャッチーなタイトル",
                        "comments": [300, 302, 321, 311, 312, -325]
                    }
                ]
                """)
        String selectTopics(String text);
    }

    public static void main(String[] args) {
        Topics topics = I.json("""

                  [
                  {
                    "title": "重い女、白伏羲？高コストスキルで王子も困惑！",
                    "comments": [
                      58,
                      66,
                      68,
                      73,
                      74,
                      76,
                      77,
                      78,
                      81,
                      82,
                      83,
                      -86,
                      89,
                      93,
                      96,
                      100,
                      101,
                      105,
                      108,
                      110,
                      119,
                      128,
                      129,
                      136,
                      147,
                      150,
                      159,
                      161,
                      169,
                      404,
                      408,
                      410,
                      411,
                      413,
                      436,
                      666,
                      -721,
                      853,
                      854,
                      856,
                      858,
                      865,
                      866,
                      870,
                      877,
                      878,
                      889,
                      894,
                      897,
                      907,
                      921,
                      925,
                      929,
                      930,
                      933,
                      973
                    ]
                  },
                  {
                    "title": "イケメン新ソルジャー「ガレア」はホモパの希望か、それとも…？",
                    "comments": [
                      404,
                      408,
                      411,
                      -423,
                      434,
                      436,
                      440,
                      443,
                      445,
                      447,
                      448,
                      449,
                      451,
                      452,
                      456,
                      457,
                      460,
                      462,
                      464,
                      465,
                      466,
                      467,
                      469,
                      471,
                      473,
                      474,
                      475,
                      476,
                      480,
                      482,
                      485,
                      486,
                      -490,
                      494,
                      -495,
                      496,
                      497,
                      501,
                      502,
                      503,
                      504,
                      505,
                      506,
                      507,
                      508,
                      509,
                      510,
                      511,
                      512,
                      513,
                      514,
                      515,
                      516,
                      517,
                      518,
                      519,
                      520,
                      521,
                      523,
                      524,
                      525,
                      526,
                      528,
                      531,
                      533,
                      534,
                      536,
                      537,
                      540,
                      546,
                      548,
                      553,
                      556,
                      557,
                      567,
                      665,
                      722,
                      726,
                      -732,
                      733,
                      734,
                      737,
                      740,
                      744,
                      745,
                      747,
                      748,
                      752,
                      759,
                      865,
                      871,
                      893,
                      990,
                      995,
                      996,
                      1000
                    ]
                  },
                  {
                    "title": "元JKケンタウロス「スズ」が危険すぎる！密猟者とショタの末路",
                    "comments": [
                      543,
                      549,
                      565,
                      572,
                      574,
                      -581,
                      585,
                      586,
                      588,
                      -589,
                      590,
                      591,
                      592,
                      593,
                      -594,
                      596,
                      597,
                      598,
                      599,
                      600,
                      601,
                      602,
                      603,
                      604,
                      605,
                      606,
                      -607,
                      -608,
                      609,
                      611,
                      613,
                      614,
                      -616,
                      622,
                      625,
                      626,
                      627,
                      628,
                      629,
                      630,
                      631,
                      634,
                      636,
                      637,
                      639
                    ]
                  },
                  {
                    "title": "コマちゃんはどこへ？蝶々を追いかけた先で悪堕ちか！？",
                    "comments": [
                      33,
                      42,
                      43,
                      44,
                      46,
                      49,
                      52,
                      612,
                      615,
                      -617,
                      618,
                      619,
                      620,
                      624,
                      627,
                      -632,
                      831,
                      835,
                      846,
                      892,
                      902
                    ]
                  },
                  {
                    "title": "アイギス世界は神も人も「おりゅ？」の対象？最凶の呪文がスレを席巻",
                    "comments": [
                      146,
                      151,
                      201,
                      -417,
                      422,
                      424,
                      426,
                      429,
                      431,
                      432,
                      435,
                      631,
                      633,
                      637,
                      638,
                      643,
                      644,
                      647,
                      648,
                      649,
                      -651,
                      654,
                      655,
                      661,
                      662,
                      668,
                      672,
                      673,
                      675,
                      676,
                      677,
                      678,
                      680,
                      681,
                      684,
                      -685,
                      686,
                      687,
                      688,
                      690,
                      691,
                      692,
                      693,
                      697,
                      698,
                      699,
                      701,
                      702,
                      703,
                      706,
                      707,
                      709,
                      710,
                      712,
                      713,
                      714,
                      715,
                      718,
                      719,
                      723,
                      724,
                      725,
                      728,
                      729,
                      730,
                      731,
                      738,
                      739,
                      741,
                      742,
                      746,
                      749,
                      851,
                      852,
                      864,
                      880,
                      891,
                      903,
                      928,
                      929,
                      932,
                      937,
                      940,
                      942,
                      947,
                      949,
                      950,
                      952,
                      953,
                      960,
                      961,
                      965,
                      -967,
                      976,
                      979,
                      981,
                      982,
                      983,
                      984,
                      986,
                      987,
                      988,
                      989,
                      990,
                      993,
                      994,
                      995,
                      996
                    ]
                  },
                  {
                    "title": "人類滅亡へのカウントダウン？花粉、サイコパス、安楽死…混沌の議論",
                    "comments": [
                      388,
                      389,
                      393,
                      394,
                      396,
                      397,
                      398,
                      399,
                      400,
                      401,
                      406,
                      525,
                      533,
                      534,
                      549,
                      603,
                      605,
                      616,
                      627,
                      767,
                      769,
                      771,
                      774,
                      776,
                      -780,
                      785,
                      786,
                      787,
                      788,
                      -789,
                      790,
                      792,
                      795,
                      796,
                      797,
                      798,
                      799,
                      801,
                      802,
                      -803,
                      804,
                      805,
                      809,
                      812,
                      814,
                      815,
                      816,
                      817,
                      819,
                      821,
                      822,
                      823,
                      824,
                      825,
                      826,
                      827,
                      830,
                      832,
                      833,
                      834,
                      837,
                      839,
                      840,
                      841,
                      843,
                      847,
                      850,
                      852,
                      855,
                      857,
                      859,
                      861,
                      862,
                      863,
                      864,
                      869,
                      873,
                      875,
                      876,
                      880,
                      882,
                      885,
                      886,
                      887,
                      888,
                      898,
                      901,
                      924
                    ]
                  },
                  {
                    "title": "マルチタスク王子、車の運転で今日も大忙し！？",
                    "comments": [
                      55,
                      57,
                      59,
                      61,
                      62,
                      64,
                      69,
                      71,
                      72,
                      -94,
                      102,
                      106,
                      115,
                      118,
                      126,
                      132,
                      318,
                      319,
                      322,
                      324,
                      419,
                      425,
                      428,
                      -349
                    ]
                  }
                ]
                                """, Topics.class);

        System.out.println(topics);
    }
}
